# name: Super-hooks

# Run this workflow every time a new commit pushed to your repository
# on:
#   push:
#     # branches: [ master ]
#     branches: []

# jobs:
#   sync-branch:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Merge master -> feature/dummy
#         uses: devmasx/merge-branch@v1.3.1
#         with:
#           type: now
#           from_branch: master
#           target_branch: feature/dummy
#           github_token: ${{ github.token }}
