name: If and set output Test

on:
  workflow_dispatch:
    inputs:
      trueorfalse:
        type: choice
        required: true
        options:
          - option_true
          - option_false

jobs:
  set_output_string:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.trueorfalse == 'option_true' }}
    outputs:
      output1: ${{ steps.trueorfalse.outputs.test }}
    steps:
      - name: echo input value
        id: trueorfalse
        run: echo "::set-output name=test::value123"
  echo_useroption_value:
    runs-on: ubuntu-latest
    needs: set_output_string
    steps:
      - name: echo useroption value
        run: echo ${{needs.set_output_string.outputs.output1}}





# jobs:
#   job1:
#     runs-on: ubuntu-latest
#     # Map a step output to a job output
#     outputs:
#       output1: ${{ steps.step1.outputs.test }}
#       output2: ${{ steps.step2.outputs.test }}
#     steps:
#       - id: step1
#         run: echo "::set-output name=test::hello"
#       - id: step2
#         run: echo "::set-output name=test::world"
#   job2:
#     runs-on: ubuntu-latest
#     needs: job1
#     steps:
#       - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
