name: Create Release Version Tag

# virtual-deploy が正常終了したら実行する
on:
  workflow_run:
    workflows:
      - virtual-deploy
    # branches:
    #   - main
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create tag
        # run: |
        #   echo "release-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)" > TAG_NAME
        #   git tag $(cat TAG_NAME)
        #   git push origin $(cat TAG_NAME)
        run: |
          TAG_NAME=release-$(TZ=Asia/Tokyo date +%Y%m%d-%H%M%S)
          git tag $TAG_NAME
          git push origin $(cat TAG_NAME)

      # - name: Set current date
      #   # id: current_date
      #   env:
      #     TZ: 'Asia/Tokyo'
      #   run: echo "current_date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      # - name: Create tag
      #   # id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: release-${{ env.current_date }}
      #     release_name: release-${{ env.current_date }}
      #     draft: false
      #     prerelease: false



