name: virtual deploy test

on:
  push:
    branches: [ master ]

jobs:
  virtual-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: echo git log
        run: git log -n 1 | cat
      - name: echo fixed message
        run: echo "deployed!"
