name: Wait Status Check
on:
  pull_request_target:
  # pull_request:
  #   types:
  #     - labeled
  #     - unlabeled
  #     - synchronize
  #     - opened
  #     - edited
  #     - ready_for_review
  #     - reopened
  #     - unlocked
  # pull_request_review:
  #   types:
  #     - submitted
  # status: {}
jobs:
  status_check:
    # name: Automerge PRs
    name: Status Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: 'Wait for status checks'
        id: waitforstatuschecks
        uses: "WyriHaximus/github-action-wait-for-status@v1.4"
        with:
          ## Note that these names are the human readable names use as status on commits, and show up as status checks on PRs.
          # ignoreActions: "Automerge PRs"
          # 自分自身を除く
          ignoreActions: "Status Check"
          # checkInterval: 13 # デフォルトで10なので書かなくてよさそう
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: debug
        run: echo ${{ steps.waitforstatuschecks.outputs.status }}
      - name: Merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        # uses: "pascalgn/automerge-action@v0.15.3"
        # if: steps.waitforstatuschecks.outputs.status == 'success'
        # # run: echo success waiting!!!!!!
        # env:
        #   GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
